issue-tracker/IssueTracker/ViewModels/StateWorkflowViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace IssueTracker.ViewModels
{
    public class StateWorkflowViewModel : BaseViewModel
    {
        // Foreign keys
        [Display(Name = "StateWorkflowFrom", ResourceType = typeof(Locale.StateWorkflowStrings))]
        public Guid FromStateId { get; set; }

        [Display(Name = "StateWorkflowTo", ResourceType = typeof(Locale.StateWorkflowStrings))]
        public Guid ToStateId { get; set; }

        // Table definitions
        public StateViewModel FromState { get; set; }
        public StateViewModel ToState { get; set; }

    }
}

issue-tracker/IssueTracker/Controllers/StateWorkflowsController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using AutoMapper;
using IssueTracker.ViewModels;
using System.Collections.Generic;
using IssueTracker.Data.Contracts.Repository_Interfaces;
using IssueTracker.Entities;
using IssueTracker.Models;

namespace IssueTracker.Controllers
{
    //[AuthorizeOrErrorPage(Roles = UserRoles.Administrators)]
    public class StateWorkflowsController : Controller
    {
        private readonly IStateWorkflowRepository _stateWorkflowRepo;
        private readonly IStateRepository _stateRepo;
        
        public StateWorkflowsController(IStateWorkflowRepository stateWorkflowRepository, IStateRepository stateRepository)
        {
            _stateWorkflowRepo = stateWorkflowRepository;
            _stateRepo = stateRepository;
        }
        // GET: StateWorkflows
        public ActionResult Index()
        {
            var stateWorkflows = _stateWorkflowRepo.GetAll().AsQueryable().Include(s => s.FromState).Include(s => s.ToState);
            foreach (var stateWorkflow in stateWorkflows)
            {
                stateWorkflow.FromState = _stateRepo.Get(stateWorkflow.FromStateId);
                stateWorkflow.ToState = _stateRepo.Get(stateWorkflow.ToStateId);
            }

            return View(Mapper.Map<IEnumerable<StateWorkflowViewModel>>(stateWorkflows).ToList());
        }

        // GET: StateWorkflows/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var stateWorkflow = _stateWorkflowRepo.Get((Guid)id);

            if (stateWorkflow == null)
            {
                return HttpNotFound();
            }

            return View(Mapper.Map<StateWorkflowViewModel>(stateWorkflow));
        }

        // GET: StateWorkflows/Create
        public ActionResult Create()
        {
            ViewBag.FromStateId = new SelectList(_stateRepo.GetAll(), "Id", "Title");
            ViewBag.ToStateId = new SelectList(_stateRepo.GetAll(), "Id", "Title");

            return View();
        }

        // POST: StateWorkflows/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FromStateId,ToStateId")] StateWorkflowViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                if (viewModel.FromStateId == viewModel.ToStateId)
                {
                    ViewBag.ErrorSameFromAndTo = Locale.StateWorkflowStrings.ErrorMessageFromToSame;
                    ViewBag.FromStateId = new SelectList(_stateRepo.GetAll(), "Id", "Title", viewModel.FromStateId);
                    ViewBag.ToStateId = new SelectList(_stateRepo.GetAll(), "Id", "Title", viewModel.ToStateId);

                    return View(viewModel);
                }

                viewModel.Id = Guid.NewGuid();

                _stateWorkflowRepo.Add(Mapper.Map<StateWorkflow>(viewModel));

                return RedirectToAction("Index");
            }

            ViewBag.FromStateId = new SelectList(_stateRepo.GetAll(), "Id", "Title", viewModel.FromStateId);
            ViewBag.ToStateId = new SelectList(_stateRepo.GetAll(), "Id", "Title", viewModel.ToStateId);

            return View(viewModel);
        }

        // GET: StateWorkflows/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var stateWorkflow = _stateWorkflowRepo.Get((Guid)id);

            if (stateWorkflow == null)
            {
                return HttpNotFound();
            }

            ViewBag.FromStateId = new SelectList(_stateRepo.GetAll(), "Id", "Title", stateWorkflow.FromStateId);
            ViewBag.ToStateId = new SelectList(_stateRepo.GetAll(), "Id", "Title", stateWorkflow.ToStateId);

            return View(Mapper.Map<StateWorkflowViewModel>(stateWorkflow));
        }

        // POST: StateWorkflows/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FromStateId,ToStateId")] StateWorkflowViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                if (viewModel.FromStateId == viewModel.ToStateId)
                {
                    ViewBag.ErrorSameFromAndTo = Locale.StateWorkflowStrings.ErrorMessageFromToSame;
                    ViewBag.FromStateId = new SelectList(_stateRepo.GetAll(), "Id", "Title", viewModel.FromStateId);
                    ViewBag.ToStateId = new SelectList(_stateRepo.GetAll(), "Id", "Title", viewModel.ToStateId);

                    return View(viewModel);
                }

                _stateWorkflowRepo.Update(Mapper.Map<StateWorkflow>(viewModel));
                
                return RedirectToAction("Index");
            }

            ViewBag.FromStateId = new SelectList(_stateRepo.GetAll(), "Id", "Title", viewModel.FromStateId);
            ViewBag.ToStateId = new SelectList(_stateRepo.GetAll(), "Id", "Title", viewModel.ToStateId);

            return View(viewModel);
        }

        // GET: StateWorkflows/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var stateWorkflow = _stateWorkflowRepo.Get((Guid)id);

            if (stateWorkflow == null)
            {
                return HttpNotFound();
            }

            return View(Mapper.Map<StateWorkflowViewModel>(stateWorkflow));
        }

        // POST: StateWorkflows/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            var stateWorkflow = _stateWorkflowRepo.Get(id);

            _stateWorkflowRepo.Remove(stateWorkflow);

            return RedirectToAction("Index");
        }

        /// <summary>
        /// Creates JSON of states and worflows within the states for GOJS visualization.
        /// </summary>
        /// <returns>JSON of states and workflows</returns>
        public JsonResult WorkflowVisualization()
        {
            var stateWorkflows = _stateWorkflowRepo.GetAll().Select(e => new {
                e.FromStateId,
                e.ToStateId
            });
            var states = _stateRepo.GetAll().Select(e => new {
                e.Id,
                e.Title,
                e.Colour
            });

            var stateDictionary = new Dictionary<Guid, string>();
            var nds = new List<object>();
            var lnks = new List<object>();

            foreach (var state in states)
            {
                stateDictionary.Add(state.Id, state.Title);
                nds.Add(new { key = state.Title, color = state.Colour });
            }

            foreach (var stateWorkflow in stateWorkflows)
            {
                string from;
                string to;

                stateDictionary.TryGetValue(stateWorkflow.FromStateId, out from);
                stateDictionary.TryGetValue(stateWorkflow.ToStateId, out to);
                
                lnks.Add(new {from, to});
            }

            var result = new { nodes = nds, links = lnks};

            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

issue-tracker/IssueTracker/Views/StateWorkflows/Create.cshtml
@model IssueTracker.ViewModels.StateWorkflowViewModel

@{
    Layout = "~/Views/Shared/_SettingsTabbedLayout.cshtml";
    ViewBag.Title = StateWorkflowStrings.TitleIndex;
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <span class="text-danger">@ViewBag.ErrorSameFromAndTo</span><br /><br />
        <div class="form-group">
            @Html.LabelFor(model => model.FromStateId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FromStateId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FromStateId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ToStateId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ToStateId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ToStateId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@SharedStrings.FormCreate" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink(SharedStrings.BackToList, "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

issue-tracker/IssueTracker/Views/StateWorkflows/Delete.cshtml
@model IssueTracker.ViewModels.StateWorkflowViewModel

@{
    Layout = "~/Views/Shared/_SettingsTabbedLayout.cshtml";
    ViewBag.Title = StateWorkflowStrings.TitleDelete;
}

<h2>@ViewBag.Title</h2>

<h3>@SharedStrings.DeleteMessageGeneric</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FromStateId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FromState.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ToStateId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ToState.Title)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="@SharedStrings.FormDelete" class="btn btn-danger" /> |
            @Html.ActionLink(SharedStrings.BackToList, "Index")
        </div>
    }
</div>

issue-tracker/IssueTracker/Views/StateWorkflows/Details.cshtml
@model IssueTracker.ViewModels.StateWorkflowViewModel

@{
    Layout = "~/Views/Shared/_SettingsTabbedLayout.cshtml";
    ViewBag.Title = StateWorkflowStrings.TitleDetails;
}

<h2>@ViewBag.Title</h2>

<div>
    <hr />
    <div id="create-button" class="float-right">
        <button type="button" class="btn btn-primary" onclick="location.href = '@Url.Action("Edit", "StateWorkflows", new {id = Model.Id})'">
            <span class="glyphicon glyphicon-edit" aria-hidden="true"></span> @SharedStrings.ButtonEdit
        </button>
        <button type="button" class="btn btn-default" onclick="location.href = '@Url.Action("Delete", "StateWorkflows", new { id = Model.Id })'">
            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> @SharedStrings.ButtonDelete
        </button>
    </div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FromStateId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FromState.Title)
        </dd>
    </dl>

    <div class="alter-position-after-buttons">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.ToStateId)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ToState.Title)
            </dd>
        </dl>
    </div>
</div>
<p>
    @Html.ActionLink(SharedStrings.BackToList, "Index")
</p>

issue-tracker/IssueTracker/Views/StateWorkflows/Edit.cshtml
@model IssueTracker.ViewModels.StateWorkflowViewModel

@{
    Layout = "~/Views/Shared/_SettingsTabbedLayout.cshtml";
    ViewBag.Title = StateWorkflowStrings.TitleEdit;
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        <span class="text-danger">@ViewBag.ErrorSameFromAndTo</span><br /><br />

        <div class="form-group">
            @Html.LabelFor(model => model.FromStateId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FromStateId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FromStateId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ToStateId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ToStateId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ToStateId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@SharedStrings.FormSave" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink(SharedStrings.BackToList, "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

issue-tracker/IssueTracker/Views/StateWorkflows/Index.cshtml
@model IEnumerable<IssueTracker.ViewModels.StateWorkflowViewModel>
@Scripts.Render("~/bundles/gojs")
@Scripts.Render("~/bundles/gojs-model")
<script>
    function gojs_create_flow() {
        jQuery.getJSON("StateWorkflows/WorkflowVisualization", load);
    }
    window.onload = gojs_init;
</script>
@{
    Layout = "~/Views/Shared/_SettingsTabbedLayout.cshtml";
    ViewBag.Title = StateWorkflowStrings.TitleIndex;
}

<h2>@ViewBag.Title</h2>
<br/>

<div id="swVisualization"></div>
<br /><br />

@if (Model.ToList().Count == 0)
{
    <i>@Html.Raw(string.Format(StateWorkflowStrings.ListNoResult, Html.ActionLink(StateWorkflowStrings.ListNoResultNew, "Create")))</i>
}
else
{
    <table class="table entity-listing">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FromStateId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ToStateId)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FromState.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ToState.Title)
                </td>
                <td>
                    @Html.ActionLink(SharedStrings.ButtonEdit, "Edit", new { id = item.Id }) |
                    @Html.ActionLink(SharedStrings.ButtonDetails, "Details", new { id = item.Id }) |
                    @Html.ActionLink(SharedStrings.ButtonDelete, "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </table>
}