issue-tracker/IssueTracker/Models/UserRoles.cs
namespace IssueTracker.Models
{
    public class UserRoles
    {
        public const string Administrators = "Administrators";
        public static UserRoles AdministratorsUserRole = new UserRoles(Administrators);
        public const string Users = "Users";
        public static UserRoles UsersUserRole = new UserRoles(Users);
        private string name;

        private UserRoles(string name)
        {
            this.name = name;
        }

        public override string ToString()
        {
            return name;
        }
    }
}

issue-tracker/IssueTracker/Controllers/IssuesController.cs
using System;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Collections.Generic;
using AutoMapper;
using IssueTracker.Entities;
using IssueTracker.ViewModels;
using PagedList;
using IssueTracker.Data.Contracts.Repository_Interfaces;
using System.Text.RegularExpressions;
using IssueTracker.Models;
using IssueTracker.Data.Services;
using IssueTracker.Data.Facade;

namespace IssueTracker.Controllers
{
    [AuthorizeOrErrorPage]
    public class IssuesController : Controller
    {
        private readonly IIssueService _issueService;
        private readonly IStateService _stateService;
        private readonly IStateWorkflowRepository _stateWorkflowRepo;
        private readonly IApplicationUserRepository _applicationUserRepo;
        private readonly IStateRepository _stateRepo;
        private readonly IProjectService _projectService;

        private const int ProjectsPerPage = 20;

        public IssuesController(IFacade facade, IStateWorkflowRepository stateWorkflowRepository, IApplicationUserRepository applicationUserRepository,
            IStateRepository stateRepository, IIssueService issueService, IStateService stateService, IProjectService projectService)
        {
            _facade = facade;
            _projectService = projectService;
            _issueService = issueService;
            _stateService = stateService;
            _stateWorkflowRepo = stateWorkflowRepository;
            _applicationUserRepo = applicationUserRepository;
            _stateRepo = stateRepository;
        }

        // GET: Issues
        public ActionResult Index(int? page, string sort, string searchName, string searchTitle,
            Guid? searchAssignee, Guid? searchReporter, Guid? searchProject, Guid? searchState, IssueType? searchType)
        {
            // viewbag items are used in the header to sort the records
            ViewBag.CreatedSort = String.IsNullOrEmpty(sort) ? "created_desc" : String.Empty;
            ViewBag.SummarySort = sort == "summary" ? "summary_desc" : "summary";
            ViewBag.ReporterSort = sort == "reporter" ? "reporter_desc" : "reporter";
            ViewBag.ProjectSort = sort == "project" ? "project_desc" : "project";
            ViewBag.AssigneeSort = sort == "assignee" ? "assignee_desc" : "assignee";
            ViewBag.StatusSort = sort == "status" ? "status_desc" : "status";
            ViewBag.IssueTypeSort = sort == "issuetype" ? "issuetype_desc" : "issuetype";

            ViewBag.SearchProject = new SelectList(_projectService.GetProjects(), "Id", "Title");
            ViewBag.SearchAssignee = ViewBag.SearchReporter = new SelectList(_applicationUserRepo.GetAll(), "Id", "Email");
            ViewBag.SearchState = new SelectList(_stateService.GetStatesOrderedByIndex(), "Id", "Title");
            
            var issuesTemp = _issueService.GetAllIssues().ToList();

            // search
            issuesTemp = searchIssues(issuesTemp, searchName, searchTitle, searchAssignee, searchReporter, searchProject, searchState, searchType);

            var issues = Mapper.Map<IEnumerable<IssueIndexViewModel>>(issuesTemp);
            issues = getSortedIssues(issues, sort);

            var pageNumber = page ?? 1;

            return View(issues.ToPagedList(pageNumber, ProjectsPerPage));
        }
        [HttpGet]
        public ActionResult GetIssue(int? page, string sort, string searchName, string searchTitle,
            Guid? searchAssignee, Guid? searchReporter, Guid? searchProject, Guid? searchState, IssueType? searchType)
        {
            var issuesTemp = _issueService.GetAllIssues().ToList();

            // search
            issuesTemp = searchIssues(issuesTemp, searchName, searchTitle, searchAssignee, searchReporter, searchProject, searchState, searchType);

            var issues = Mapper.Map<IEnumerable<IssueIndexViewModel>>(issuesTemp);
            
            return Json(issues);
        }

        private static List<Issue> searchIssues(List<Issue> issues, string searchName, string searchTitle,
            Guid? searchAssignee, Guid? searchReporter, Guid? searchProject, Guid? searchState, IssueType? searchType)
        {
            if (!string.IsNullOrEmpty(searchName))
            {
                issues = issues.Where(s => s.Name.ToLower().Contains(searchName.ToLower())).ToList();
            }

            if (!string.IsNullOrEmpty(searchTitle))
            {
                issues = issues.Where(s => (s.Project.Code + s.CodeNumber + ": " + s.Name).ToLower().Contains(searchTitle.ToLower())).ToList();
            }

            if (searchAssignee != null)
            {
                issues = issues.Where(s => s.AssigneeId == searchAssignee).ToList();
            }

            if (searchReporter != null)
            {
                issues = issues.Where(s => s.ReporterId == searchReporter).ToList();
            }

            if (searchProject != null)
            {
                issues = issues.Where(s => s.ProjectId == searchProject).ToList();
            }

            if (searchState != null)
            {
                issues = issues.Where(s => s.StateId == searchState).ToList();
            }

            if (searchType != null)
            {
                issues = issues.Where(s => s.Type == searchType).ToList();
            }

            return issues;
        }

        private readonly UsersByEmailComparer _usersComparer = new UsersByEmailComparer();
        private readonly ProjectsByTitleComparer _projectsComparer = new ProjectsByTitleComparer();
        private readonly StatesByTitleComparer _statesComparer = new StatesByTitleComparer();
        private readonly IFacade _facade;

        private IEnumerable<IssueIndexViewModel> getSortedIssues(IEnumerable<IssueIndexViewModel> issues, string sortKey)
        {
            switch (sortKey)
            {
                case "summary":
                    return issues.OrderBy(ii => ii.Name);
                case "summary_desc":
                    return issues.OrderByDescending(ii => ii.Name);
                case "reporter_desc":
                    return issues.OrderByDescending(ii => ii.Reporter, _usersComparer);
                case "reporter":
                    return issues.OrderBy(ii => ii.Reporter, _usersComparer);
                case "status_desc":
                    return issues.OrderByDescending(ii => ii.State, _statesComparer);
                case "status":
                    return issues.OrderBy(ii => ii.State, _statesComparer);
                case "assignee_desc":
                    return issues.OrderByDescending(ii => ii.Assignee, _usersComparer);
                case "assignee":
                    return issues.OrderBy(ii => ii.Assignee, _usersComparer);
                case "project_desc":
                    return issues.OrderByDescending(ii => ii.Project, _projectsComparer);
                case "project":
                    return issues.OrderBy(ii => ii.Project, _projectsComparer);
                case "created_desc":
                    return issues.OrderByDescending(ii => ii.Created);
                case "issuetype":
                    return issues.OrderBy(ii => ii.Type);
                case "issuetype_desc":
                    return issues.OrderByDescending(ii => ii.Type);
                default:
                    return issues.OrderBy(ii => ii.Created);
            }
        }

        private class UsersByEmailComparer : IComparer<ApplicationUser>
        {
            public int Compare(ApplicationUser x, ApplicationUser y)
            {
                if (x == null && y == null)
                {
                    return 0;
                } 
                else if (x == null && y != null)
                {
                    return 1;
                }
                else if (x != null && y == null)
                {
                    return -1;
                }
                return x.Email.CompareTo(y.Email);
            }
        }

        private class ProjectsByTitleComparer : IComparer<ProjectViewModel>
        {
            public int Compare(ProjectViewModel x, ProjectViewModel y)
            {
                return x.Title.CompareTo(y.Title);
            }
        }

        private class StatesByTitleComparer : IComparer<StateViewModel>
        {
            public int Compare(StateViewModel x, StateViewModel y)
            {
                return x.Title.CompareTo(y.Title);
            }
        }

        // GET: Issues/Details/5
        public ActionResult Details(string id, IssueSubDetail? sub)
        {
            var code = IssueCode.Parse(id);
            if (code == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var issue = _issueService.GetByProjectCodeAndIssueNumber(code.ProjectCode, code.IssueNumber);

            var viewModel = new IssueDetailViewModel
            {
                Issue = Mapper.Map<IssueIndexViewModel>(issue)
            };

            if (viewModel.Issue == null)
            {
                return HttpNotFound();
            }

            // possible workflows
            var workflows = _stateWorkflowRepo.GetPossibleWorkflows(viewModel.Issue.State.Id);
            foreach (var stateWorkflow in workflows)
            {
                stateWorkflow.ToState = _stateRepo.Get(stateWorkflow.ToStateId);
            }
            viewModel.StateWorkflows = Mapper.Map<IEnumerable<StateWorkflowViewModel>>(workflows);

            // comments from all versions of the issue
            var comments = _issueService.GetCommentsForIssue(issue.Id);

            viewModel.Comments = Mapper.Map<IEnumerable<CommentViewModel>>(comments);
            foreach (var comment in viewModel.Comments)
            {
                comment.User = _applicationUserRepo.Get(comment.AuthorId);
            }

            viewModel.Changes = getHistory(viewModel.Issue.Id, comments);

issue-tracker/IssueTracker/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IssueTracker.Controllers
{
    [AuthorizeOrErrorPage]
    public class RolesController : Controller
    {
        // GET: Roles
        public ActionResult Index()
        {
            return View();
        }
    }
}

issue-tracker/IssueTracker/Views/Roles/EditList.cshtml
@{
    ViewBag.Title = "EditList";
}

<h2>EditList</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.Hidden("load-project-users-url", @Url.Action("LoadProjectUsers", "Issues"), new { @id = "LoadProjectUsersUrl" })
        <span class="text-danger">@ViewBag.ErrorSQL</span>
        <span class="text-danger">@ViewBag.ErrorInvalidProject</span>
        <br /><br />

        <div class="form-group">
            <label class="control-label col-md-2">Description</label>
            <div class="col-md-10">
                <input type="text" ng-model="nCoupon.Description" id='n-Description' ng-disabled="locationNotSelected" required />
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Name</label>
            <div class="col-md-10">
                <input type="text" ng-model="nCoupon.Description" id='n-Description' ng-disabled="locationNotSelected" required />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="save" class="btn btn-default" />
            </div>
        </div>

    </div>
}



<div>
    @Html.ActionLink(SharedStrings.BackToList, "Index")
</div>

issue-tracker/IssueTracker/Views/Roles/index.cshtml
<div><ng-view></ng-view></div>

<script type="text/ng-template" id="roledetails">
    <ul class="nav nav-tabs">
        <li id="create-button">
            <a class="btn btn-primary" aria-hidden="true" href="#/editroles/{{id}}">
                <span class="glyphicon glyphicon-edit" aria-hidden="true">Edit</span>
            </a>
            <button type="button" class="btn btn-primary" aria-hidden="true" ng-click="deleteRole()">
                <span class="glyphicon glyphicon-remove" aria-hidden="true">Delete</span>
            </button>
        </li>
    </ul>
    <dl class="dl-horizontal">
        <dt>
            Id
        </dt>
        <dd>
            {{role.Id}}
        </dd>
    </dl>
    <dl class="dl-horizontal">
        <dt>
            Name
        </dt>

        <dd>
            {{role.Name}}
        </dd>
    </dl>
    <dl class="dl-horizontal">
        <dt>
            Description
        </dt>

        <dd>
            {{role.Description}}
        </dd>
    </dl>
</script>

<script type="text/ng-template" id="RoleList">
    <h2>Roles</h2>
    <hr />
    <ul class="nav nav-tabs">
        <li id="create-button">
            <a type="button" class="btn btn-primary" href="#/addroles">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> @SharedStrings.ButtonAdd
            </a>

        </li>
    </ul>

    <table class="table">
        <tr>
            <th>
                Name
            </th>
            <th>
                Description
            </th>
        </tr>
        <tr ng-repeat="item in RolesList">
            <td>
                <a href="#/roledetails/{{item.Id}}">{{item.Name}}</a>
            </td>
            <td>
                {{item.Description}}
            </td>
        </tr>
    </table>
</script>
<script type="text/ng-template" id="addroles">
    <h2>{{isEdit==true?'Edit Role':'Add Role'}}</h2>
    <hr />

    <div class="form-horizontal">
        <div class="form-group">
            <label class="control-label col-md-2">Name</label>
            <div class="col-md-10">
                <input type="text" ng-model="role.Name" id='n-name' required />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Description</label>
            <div class="col-md-10">
                <textarea rows="5" cols="50" ng-model="role.Description">
                </textarea>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button class="btn btn-default" ng-click="isEdit==true?updateRoles():createRoles()">{{isEdit==true?'Update':'Create'}}</button>
            </div>
        </div>

    </div>
    <div>
        <a href="#/Roles">BackToList</a>
    </div>
</script>


<script type="text/javascript">
    roles.config(function ($routeProvider) {
        $routeProvider
            .when('/Roles', {
                templateUrl: 'RoleList',
                controller: 'RoleListController'
            })
            .when('/addroles', {
                templateUrl: 'addroles',
                controller:"RolesController"
            })
            .when('/roledetails/:id', {
                templateUrl: 'roledetails',
                controller: "RolesDetailsController"
            })
            .when('/editroles/:id', {
                templateUrl: 'addroles',
                controller: "RolesController"
            })
            .otherwise({
                redirectTo: '/Roles'
            });
        });
    roles.controller("RoleListController", function ($scope, roleService) {

        roleService.getRoles().then(function (response) {
            $scope.RolesList = response;
        });
    });
    roles.controller("RolesController", function ($scope, roleService, $routeParams) {
        $scope.isEdit = false;
        $scope.role = {};
        if($routeParams.id)
        {
            $scope.isEdit = true;
            roleService.getRolesDetails($routeParams.id).then(function (response) {
                $scope.role = response[0];
            },
            function (error) {
            });

            $scope.updateRoles = function () {
                roleService.updateRoles($scope.role).then(function (response) {
                    alert(response);
                    window.location.href = "#/Roles";
                },
                function (error) {
                });
            };


        }
        else
        {
            $scope.createRoles = function () {
                roleService.createRoles($scope.role).then(function (response) {
                    alert(response);
                    window.location.href = "#/Roles";
                },
                function (error) {
                });
            };
        }
    });
    roles.controller("RolesDetailsController", function ($scope, roleService, $routeParams) {
        $scope.id = $routeParams.id;
        if ($routeParams.id) {
            roleService.getRolesDetails($routeParams.id).then(function (response) {
                $scope.role = response[0];                
            },
            function (error) {
            });
            $scope.deleteRole = function () {
                if ($scope.id && confirm("Are you sure, want to delete the Role?")) {
                    roleService.deleteRole($scope.id).then(function (response) {
                        alert(response);
                        window.location.href = "#/Roles";
                    }, function (error) {
                    });
                }
            }
        }
    });
</script>